/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { Question } from '../model';
// @ts-ignore
import type { QuestionSubmit } from '../model';
// @ts-ignore
import type { QuestionSubmitVO } from '../model';
// @ts-ignore
import type { User } from '../model';
/**
 * InnerQuestionControllerApi - axios parameter creator
 */
export const InnerQuestionControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {string} questionId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getQuestionById: async (questionId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'questionId' is not null or undefined
            assertParamExists('getQuestionById', 'questionId', questionId)
            const localVarPath = `/inner/get/id`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (questionId !== undefined) {
                localVarQueryParameter['questionId'] = questionId;
            }

            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} questionSubmitId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getQuestionSubmitById: async (questionSubmitId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'questionSubmitId' is not null or undefined
            assertParamExists('getQuestionSubmitById', 'questionSubmitId', questionSubmitId)
            const localVarPath = `/inner/submit/update/id`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (questionSubmitId !== undefined) {
                localVarQueryParameter['questionSubmitId'] = questionSubmitId;
            }

            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {User} loginUser 
         * @param {QuestionSubmit} questionSubmit 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getQuestionSubmitVO: async (loginUser: User, questionSubmit: QuestionSubmit, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'loginUser' is not null or undefined
            assertParamExists('getQuestionSubmitVO', 'loginUser', loginUser)
            // verify required parameter 'questionSubmit' is not null or undefined
            assertParamExists('getQuestionSubmitVO', 'questionSubmit', questionSubmit)
            const localVarPath = `/inner/submit/get/vo`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (loginUser !== undefined) {
                for (const [key, value] of Object.entries(loginUser)) {
                    localVarQueryParameter[key] = value;
                }
            }

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(questionSubmit, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {QuestionSubmit} questionSubmit 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateQuestionSubmitById: async (questionSubmit: QuestionSubmit, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'questionSubmit' is not null or undefined
            assertParamExists('updateQuestionSubmitById', 'questionSubmit', questionSubmit)
            const localVarPath = `/inner/submit/update`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(questionSubmit, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * InnerQuestionControllerApi - functional programming interface
 */
export const InnerQuestionControllerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = InnerQuestionControllerApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {string} questionId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getQuestionById(questionId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Question>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getQuestionById(questionId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['InnerQuestionControllerApi.getQuestionById']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} questionSubmitId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getQuestionSubmitById(questionSubmitId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<QuestionSubmit>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getQuestionSubmitById(questionSubmitId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['InnerQuestionControllerApi.getQuestionSubmitById']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {User} loginUser 
         * @param {QuestionSubmit} questionSubmit 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getQuestionSubmitVO(loginUser: User, questionSubmit: QuestionSubmit, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<QuestionSubmitVO>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getQuestionSubmitVO(loginUser, questionSubmit, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['InnerQuestionControllerApi.getQuestionSubmitVO']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {QuestionSubmit} questionSubmit 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateQuestionSubmitById(questionSubmit: QuestionSubmit, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<boolean>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateQuestionSubmitById(questionSubmit, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['InnerQuestionControllerApi.updateQuestionSubmitById']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * InnerQuestionControllerApi - factory interface
 */
export const InnerQuestionControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = InnerQuestionControllerApiFp(configuration)
    return {
        /**
         * 
         * @param {string} questionId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getQuestionById(questionId: string, options?: RawAxiosRequestConfig): AxiosPromise<Question> {
            return localVarFp.getQuestionById(questionId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} questionSubmitId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getQuestionSubmitById(questionSubmitId: string, options?: RawAxiosRequestConfig): AxiosPromise<QuestionSubmit> {
            return localVarFp.getQuestionSubmitById(questionSubmitId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {User} loginUser 
         * @param {QuestionSubmit} questionSubmit 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getQuestionSubmitVO(loginUser: User, questionSubmit: QuestionSubmit, options?: RawAxiosRequestConfig): AxiosPromise<QuestionSubmitVO> {
            return localVarFp.getQuestionSubmitVO(loginUser, questionSubmit, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {QuestionSubmit} questionSubmit 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateQuestionSubmitById(questionSubmit: QuestionSubmit, options?: RawAxiosRequestConfig): AxiosPromise<boolean> {
            return localVarFp.updateQuestionSubmitById(questionSubmit, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * InnerQuestionControllerApi - object-oriented interface
 */
export class InnerQuestionControllerApi extends BaseAPI {
    /**
     * 
     * @param {string} questionId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getQuestionById(questionId: string, options?: RawAxiosRequestConfig) {
        return InnerQuestionControllerApiFp(this.configuration).getQuestionById(questionId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} questionSubmitId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getQuestionSubmitById(questionSubmitId: string, options?: RawAxiosRequestConfig) {
        return InnerQuestionControllerApiFp(this.configuration).getQuestionSubmitById(questionSubmitId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {User} loginUser 
     * @param {QuestionSubmit} questionSubmit 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getQuestionSubmitVO(loginUser: User, questionSubmit: QuestionSubmit, options?: RawAxiosRequestConfig) {
        return InnerQuestionControllerApiFp(this.configuration).getQuestionSubmitVO(loginUser, questionSubmit, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {QuestionSubmit} questionSubmit 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public updateQuestionSubmitById(questionSubmit: QuestionSubmit, options?: RawAxiosRequestConfig) {
        return InnerQuestionControllerApiFp(this.configuration).updateQuestionSubmitById(questionSubmit, options).then((request) => request(this.axios, this.basePath));
    }
}

