/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { BaseResponseBoolean } from '../model';
// @ts-ignore
import type { BaseResponseListQuestionSubmit } from '../model';
// @ts-ignore
import type { BaseResponseLong } from '../model';
// @ts-ignore
import type { BaseResponsePageQuestion } from '../model';
// @ts-ignore
import type { BaseResponsePageQuestionSubmitVO } from '../model';
// @ts-ignore
import type { BaseResponsePageQuestionVO } from '../model';
// @ts-ignore
import type { BaseResponseQuestion } from '../model';
// @ts-ignore
import type { BaseResponseQuestionSubmitVO } from '../model';
// @ts-ignore
import type { BaseResponseQuestionVO } from '../model';
// @ts-ignore
import type { DeleteRequest } from '../model';
// @ts-ignore
import type { QuestionAddRequest } from '../model';
// @ts-ignore
import type { QuestionEditRequest } from '../model';
// @ts-ignore
import type { QuestionQueryRequest } from '../model';
// @ts-ignore
import type { QuestionSubmitAddRequest } from '../model';
// @ts-ignore
import type { QuestionSubmitQueryRequest } from '../model';
// @ts-ignore
import type { QuestionUpdateRequest } from '../model';
/**
 * QuestionControllerApi - axios parameter creator
 */
export const QuestionControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {QuestionAddRequest} questionAddRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addQuestion: async (questionAddRequest: QuestionAddRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'questionAddRequest' is not null or undefined
            assertParamExists('addQuestion', 'questionAddRequest', questionAddRequest)
            const localVarPath = `/add`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(questionAddRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {DeleteRequest} deleteRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteQuestion: async (deleteRequest: DeleteRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'deleteRequest' is not null or undefined
            assertParamExists('deleteQuestion', 'deleteRequest', deleteRequest)
            const localVarPath = `/delete`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(deleteRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {QuestionSubmitAddRequest} questionSubmitAddRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        doQuestionSubmit: async (questionSubmitAddRequest: QuestionSubmitAddRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'questionSubmitAddRequest' is not null or undefined
            assertParamExists('doQuestionSubmit', 'questionSubmitAddRequest', questionSubmitAddRequest)
            const localVarPath = `/submit`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(questionSubmitAddRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {QuestionEditRequest} questionEditRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        editQuestion: async (questionEditRequest: QuestionEditRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'questionEditRequest' is not null or undefined
            assertParamExists('editQuestion', 'questionEditRequest', questionEditRequest)
            const localVarPath = `/edit`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(questionEditRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllQuestionSubmitByList: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/submit/admin/list`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getQuestionById1: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('getQuestionById1', 'id', id)
            const localVarPath = `/get/all`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (id !== undefined) {
                localVarQueryParameter['id'] = id;
            }

            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {QuestionQueryRequest} questionQueryRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getQuestionList: async (questionQueryRequest: QuestionQueryRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'questionQueryRequest' is not null or undefined
            assertParamExists('getQuestionList', 'questionQueryRequest', questionQueryRequest)
            const localVarPath = `/list/admin-page`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(questionQueryRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getQuestionVOById: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('getQuestionVOById', 'id', id)
            const localVarPath = `/get/vo`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (id !== undefined) {
                localVarQueryParameter['id'] = id;
            }

            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} submitId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSubmit: async (submitId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'submitId' is not null or undefined
            assertParamExists('getSubmit', 'submitId', submitId)
            const localVarPath = `/submit/getSubmitStatus`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (submitId !== undefined) {
                localVarQueryParameter['submitId'] = submitId;
            }

            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {QuestionQueryRequest} questionQueryRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listMyQuestionVOByPage: async (questionQueryRequest: QuestionQueryRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'questionQueryRequest' is not null or undefined
            assertParamExists('listMyQuestionVOByPage', 'questionQueryRequest', questionQueryRequest)
            const localVarPath = `/my/list/page/vo`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(questionQueryRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {QuestionQueryRequest} questionQueryRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listQuestionByPage: async (questionQueryRequest: QuestionQueryRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'questionQueryRequest' is not null or undefined
            assertParamExists('listQuestionByPage', 'questionQueryRequest', questionQueryRequest)
            const localVarPath = `/list/page`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(questionQueryRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {QuestionSubmitQueryRequest} questionSubmitQueryRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listQuestionSubmitByPage: async (questionSubmitQueryRequest: QuestionSubmitQueryRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'questionSubmitQueryRequest' is not null or undefined
            assertParamExists('listQuestionSubmitByPage', 'questionSubmitQueryRequest', questionSubmitQueryRequest)
            const localVarPath = `/submit/admin/page`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(questionSubmitQueryRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {QuestionQueryRequest} questionQueryRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listQuestionVOByPage: async (questionQueryRequest: QuestionQueryRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'questionQueryRequest' is not null or undefined
            assertParamExists('listQuestionVOByPage', 'questionQueryRequest', questionQueryRequest)
            const localVarPath = `/list/page/vo`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(questionQueryRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {QuestionUpdateRequest} questionUpdateRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateQuestion: async (questionUpdateRequest: QuestionUpdateRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'questionUpdateRequest' is not null or undefined
            assertParamExists('updateQuestion', 'questionUpdateRequest', questionUpdateRequest)
            const localVarPath = `/update`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(questionUpdateRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * QuestionControllerApi - functional programming interface
 */
export const QuestionControllerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = QuestionControllerApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {QuestionAddRequest} questionAddRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async addQuestion(questionAddRequest: QuestionAddRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseLong>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.addQuestion(questionAddRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['QuestionControllerApi.addQuestion']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {DeleteRequest} deleteRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteQuestion(deleteRequest: DeleteRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseBoolean>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteQuestion(deleteRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['QuestionControllerApi.deleteQuestion']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {QuestionSubmitAddRequest} questionSubmitAddRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async doQuestionSubmit(questionSubmitAddRequest: QuestionSubmitAddRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseLong>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.doQuestionSubmit(questionSubmitAddRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['QuestionControllerApi.doQuestionSubmit']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {QuestionEditRequest} questionEditRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async editQuestion(questionEditRequest: QuestionEditRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseBoolean>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.editQuestion(questionEditRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['QuestionControllerApi.editQuestion']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAllQuestionSubmitByList(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseListQuestionSubmit>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAllQuestionSubmitByList(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['QuestionControllerApi.getAllQuestionSubmitByList']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getQuestionById1(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseQuestion>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getQuestionById1(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['QuestionControllerApi.getQuestionById1']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {QuestionQueryRequest} questionQueryRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getQuestionList(questionQueryRequest: QuestionQueryRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponsePageQuestion>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getQuestionList(questionQueryRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['QuestionControllerApi.getQuestionList']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getQuestionVOById(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseQuestionVO>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getQuestionVOById(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['QuestionControllerApi.getQuestionVOById']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} submitId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getSubmit(submitId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseQuestionSubmitVO>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getSubmit(submitId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['QuestionControllerApi.getSubmit']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {QuestionQueryRequest} questionQueryRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listMyQuestionVOByPage(questionQueryRequest: QuestionQueryRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponsePageQuestionVO>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listMyQuestionVOByPage(questionQueryRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['QuestionControllerApi.listMyQuestionVOByPage']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {QuestionQueryRequest} questionQueryRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listQuestionByPage(questionQueryRequest: QuestionQueryRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponsePageQuestion>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listQuestionByPage(questionQueryRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['QuestionControllerApi.listQuestionByPage']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {QuestionSubmitQueryRequest} questionSubmitQueryRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listQuestionSubmitByPage(questionSubmitQueryRequest: QuestionSubmitQueryRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponsePageQuestionSubmitVO>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listQuestionSubmitByPage(questionSubmitQueryRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['QuestionControllerApi.listQuestionSubmitByPage']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {QuestionQueryRequest} questionQueryRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listQuestionVOByPage(questionQueryRequest: QuestionQueryRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponsePageQuestionVO>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listQuestionVOByPage(questionQueryRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['QuestionControllerApi.listQuestionVOByPage']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {QuestionUpdateRequest} questionUpdateRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateQuestion(questionUpdateRequest: QuestionUpdateRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseBoolean>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateQuestion(questionUpdateRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['QuestionControllerApi.updateQuestion']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * QuestionControllerApi - factory interface
 */
export const QuestionControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = QuestionControllerApiFp(configuration)
    return {
        /**
         * 
         * @param {QuestionAddRequest} questionAddRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addQuestion(questionAddRequest: QuestionAddRequest, options?: RawAxiosRequestConfig): AxiosPromise<BaseResponseLong> {
            return localVarFp.addQuestion(questionAddRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {DeleteRequest} deleteRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteQuestion(deleteRequest: DeleteRequest, options?: RawAxiosRequestConfig): AxiosPromise<BaseResponseBoolean> {
            return localVarFp.deleteQuestion(deleteRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {QuestionSubmitAddRequest} questionSubmitAddRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        doQuestionSubmit(questionSubmitAddRequest: QuestionSubmitAddRequest, options?: RawAxiosRequestConfig): AxiosPromise<BaseResponseLong> {
            return localVarFp.doQuestionSubmit(questionSubmitAddRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {QuestionEditRequest} questionEditRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        editQuestion(questionEditRequest: QuestionEditRequest, options?: RawAxiosRequestConfig): AxiosPromise<BaseResponseBoolean> {
            return localVarFp.editQuestion(questionEditRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllQuestionSubmitByList(options?: RawAxiosRequestConfig): AxiosPromise<BaseResponseListQuestionSubmit> {
            return localVarFp.getAllQuestionSubmitByList(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getQuestionById1(id: string, options?: RawAxiosRequestConfig): AxiosPromise<BaseResponseQuestion> {
            return localVarFp.getQuestionById1(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {QuestionQueryRequest} questionQueryRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getQuestionList(questionQueryRequest: QuestionQueryRequest, options?: RawAxiosRequestConfig): AxiosPromise<BaseResponsePageQuestion> {
            return localVarFp.getQuestionList(questionQueryRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getQuestionVOById(id: string, options?: RawAxiosRequestConfig): AxiosPromise<BaseResponseQuestionVO> {
            return localVarFp.getQuestionVOById(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} submitId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSubmit(submitId: string, options?: RawAxiosRequestConfig): AxiosPromise<BaseResponseQuestionSubmitVO> {
            return localVarFp.getSubmit(submitId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {QuestionQueryRequest} questionQueryRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listMyQuestionVOByPage(questionQueryRequest: QuestionQueryRequest, options?: RawAxiosRequestConfig): AxiosPromise<BaseResponsePageQuestionVO> {
            return localVarFp.listMyQuestionVOByPage(questionQueryRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {QuestionQueryRequest} questionQueryRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listQuestionByPage(questionQueryRequest: QuestionQueryRequest, options?: RawAxiosRequestConfig): AxiosPromise<BaseResponsePageQuestion> {
            return localVarFp.listQuestionByPage(questionQueryRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {QuestionSubmitQueryRequest} questionSubmitQueryRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listQuestionSubmitByPage(questionSubmitQueryRequest: QuestionSubmitQueryRequest, options?: RawAxiosRequestConfig): AxiosPromise<BaseResponsePageQuestionSubmitVO> {
            return localVarFp.listQuestionSubmitByPage(questionSubmitQueryRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {QuestionQueryRequest} questionQueryRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listQuestionVOByPage(questionQueryRequest: QuestionQueryRequest, options?: RawAxiosRequestConfig): AxiosPromise<BaseResponsePageQuestionVO> {
            return localVarFp.listQuestionVOByPage(questionQueryRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {QuestionUpdateRequest} questionUpdateRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateQuestion(questionUpdateRequest: QuestionUpdateRequest, options?: RawAxiosRequestConfig): AxiosPromise<BaseResponseBoolean> {
            return localVarFp.updateQuestion(questionUpdateRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * QuestionControllerApi - object-oriented interface
 */
export class QuestionControllerApi extends BaseAPI {
    /**
     * 
     * @param {QuestionAddRequest} questionAddRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public addQuestion(questionAddRequest: QuestionAddRequest, options?: RawAxiosRequestConfig) {
        return QuestionControllerApiFp(this.configuration).addQuestion(questionAddRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {DeleteRequest} deleteRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public deleteQuestion(deleteRequest: DeleteRequest, options?: RawAxiosRequestConfig) {
        return QuestionControllerApiFp(this.configuration).deleteQuestion(deleteRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {QuestionSubmitAddRequest} questionSubmitAddRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public doQuestionSubmit(questionSubmitAddRequest: QuestionSubmitAddRequest, options?: RawAxiosRequestConfig) {
        return QuestionControllerApiFp(this.configuration).doQuestionSubmit(questionSubmitAddRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {QuestionEditRequest} questionEditRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public editQuestion(questionEditRequest: QuestionEditRequest, options?: RawAxiosRequestConfig) {
        return QuestionControllerApiFp(this.configuration).editQuestion(questionEditRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getAllQuestionSubmitByList(options?: RawAxiosRequestConfig) {
        return QuestionControllerApiFp(this.configuration).getAllQuestionSubmitByList(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getQuestionById1(id: string, options?: RawAxiosRequestConfig) {
        return QuestionControllerApiFp(this.configuration).getQuestionById1(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {QuestionQueryRequest} questionQueryRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getQuestionList(questionQueryRequest: QuestionQueryRequest, options?: RawAxiosRequestConfig) {
        return QuestionControllerApiFp(this.configuration).getQuestionList(questionQueryRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getQuestionVOById(id: string, options?: RawAxiosRequestConfig) {
        return QuestionControllerApiFp(this.configuration).getQuestionVOById(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} submitId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getSubmit(submitId: string, options?: RawAxiosRequestConfig) {
        return QuestionControllerApiFp(this.configuration).getSubmit(submitId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {QuestionQueryRequest} questionQueryRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public listMyQuestionVOByPage(questionQueryRequest: QuestionQueryRequest, options?: RawAxiosRequestConfig) {
        return QuestionControllerApiFp(this.configuration).listMyQuestionVOByPage(questionQueryRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {QuestionQueryRequest} questionQueryRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public listQuestionByPage(questionQueryRequest: QuestionQueryRequest, options?: RawAxiosRequestConfig) {
        return QuestionControllerApiFp(this.configuration).listQuestionByPage(questionQueryRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {QuestionSubmitQueryRequest} questionSubmitQueryRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public listQuestionSubmitByPage(questionSubmitQueryRequest: QuestionSubmitQueryRequest, options?: RawAxiosRequestConfig) {
        return QuestionControllerApiFp(this.configuration).listQuestionSubmitByPage(questionSubmitQueryRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {QuestionQueryRequest} questionQueryRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public listQuestionVOByPage(questionQueryRequest: QuestionQueryRequest, options?: RawAxiosRequestConfig) {
        return QuestionControllerApiFp(this.configuration).listQuestionVOByPage(questionQueryRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {QuestionUpdateRequest} questionUpdateRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public updateQuestion(questionUpdateRequest: QuestionUpdateRequest, options?: RawAxiosRequestConfig) {
        return QuestionControllerApiFp(this.configuration).updateQuestion(questionUpdateRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

