/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { BaseResponseBoolean } from '../model';
// @ts-ignore
import type { BaseResponseLong } from '../model';
// @ts-ignore
import type { BaseResponsePageQuestionSet } from '../model';
// @ts-ignore
import type { BaseResponsePageQuestionSetVO } from '../model';
// @ts-ignore
import type { BaseResponseQuestionSet } from '../model';
// @ts-ignore
import type { BaseResponseQuestionSetVO } from '../model';
// @ts-ignore
import type { DeleteRequest } from '../model';
// @ts-ignore
import type { QuestionSetAddRequest } from '../model';
// @ts-ignore
import type { QuestionSetEditRequest } from '../model';
// @ts-ignore
import type { QuestionSetItemAddRequest } from '../model';
// @ts-ignore
import type { QuestionSetItemRemoveRequest } from '../model';
// @ts-ignore
import type { QuestionSetQueryRequest } from '../model';
// @ts-ignore
import type { QuestionSetUpdateRequest } from '../model';
/**
 * QuestionSetControllerApi - axios parameter creator
 */
export const QuestionSetControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {QuestionSetAddRequest} questionSetAddRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addQuestionSet: async (questionSetAddRequest: QuestionSetAddRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'questionSetAddRequest' is not null or undefined
            assertParamExists('addQuestionSet', 'questionSetAddRequest', questionSetAddRequest)
            const localVarPath = `/questionSet/add`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(questionSetAddRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {QuestionSetItemAddRequest} questionSetItemAddRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addQuestionToSet: async (questionSetItemAddRequest: QuestionSetItemAddRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'questionSetItemAddRequest' is not null or undefined
            assertParamExists('addQuestionToSet', 'questionSetItemAddRequest', questionSetItemAddRequest)
            const localVarPath = `/questionSet/item/add`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(questionSetItemAddRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {DeleteRequest} deleteRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteQuestionSet: async (deleteRequest: DeleteRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'deleteRequest' is not null or undefined
            assertParamExists('deleteQuestionSet', 'deleteRequest', deleteRequest)
            const localVarPath = `/questionSet/delete`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(deleteRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {QuestionSetEditRequest} questionSetEditRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        editQuestionSet: async (questionSetEditRequest: QuestionSetEditRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'questionSetEditRequest' is not null or undefined
            assertParamExists('editQuestionSet', 'questionSetEditRequest', questionSetEditRequest)
            const localVarPath = `/questionSet/edit`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(questionSetEditRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getQuestionSetById: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('getQuestionSetById', 'id', id)
            const localVarPath = `/questionSet/get`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (id !== undefined) {
                localVarQueryParameter['id'] = id;
            }

            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getQuestionSetVOById: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('getQuestionSetVOById', 'id', id)
            const localVarPath = `/questionSet/get/vo`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (id !== undefined) {
                localVarQueryParameter['id'] = id;
            }

            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {QuestionSetQueryRequest} questionSetQueryRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listMyQuestionSetVOByPage: async (questionSetQueryRequest: QuestionSetQueryRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'questionSetQueryRequest' is not null or undefined
            assertParamExists('listMyQuestionSetVOByPage', 'questionSetQueryRequest', questionSetQueryRequest)
            const localVarPath = `/questionSet/my/list/page/vo`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(questionSetQueryRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {QuestionSetQueryRequest} questionSetQueryRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listQuestionSetByPage: async (questionSetQueryRequest: QuestionSetQueryRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'questionSetQueryRequest' is not null or undefined
            assertParamExists('listQuestionSetByPage', 'questionSetQueryRequest', questionSetQueryRequest)
            const localVarPath = `/questionSet/list/page`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(questionSetQueryRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {QuestionSetQueryRequest} questionSetQueryRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listQuestionSetVOByPage: async (questionSetQueryRequest: QuestionSetQueryRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'questionSetQueryRequest' is not null or undefined
            assertParamExists('listQuestionSetVOByPage', 'questionSetQueryRequest', questionSetQueryRequest)
            const localVarPath = `/questionSet/list/page/vo`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(questionSetQueryRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        redirectDocHtml: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/questionSet/doc.html`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        redirectOpenApiDocs: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/questionSet/v3/api-docs`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {QuestionSetItemRemoveRequest} questionSetItemRemoveRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        removeQuestionFromSet: async (questionSetItemRemoveRequest: QuestionSetItemRemoveRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'questionSetItemRemoveRequest' is not null or undefined
            assertParamExists('removeQuestionFromSet', 'questionSetItemRemoveRequest', questionSetItemRemoveRequest)
            const localVarPath = `/questionSet/item/remove`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(questionSetItemRemoveRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {QuestionSetUpdateRequest} questionSetUpdateRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateQuestionSet: async (questionSetUpdateRequest: QuestionSetUpdateRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'questionSetUpdateRequest' is not null or undefined
            assertParamExists('updateQuestionSet', 'questionSetUpdateRequest', questionSetUpdateRequest)
            const localVarPath = `/questionSet/update`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(questionSetUpdateRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * QuestionSetControllerApi - functional programming interface
 */
export const QuestionSetControllerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = QuestionSetControllerApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {QuestionSetAddRequest} questionSetAddRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async addQuestionSet(questionSetAddRequest: QuestionSetAddRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseLong>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.addQuestionSet(questionSetAddRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['QuestionSetControllerApi.addQuestionSet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {QuestionSetItemAddRequest} questionSetItemAddRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async addQuestionToSet(questionSetItemAddRequest: QuestionSetItemAddRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseBoolean>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.addQuestionToSet(questionSetItemAddRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['QuestionSetControllerApi.addQuestionToSet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {DeleteRequest} deleteRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteQuestionSet(deleteRequest: DeleteRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseBoolean>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteQuestionSet(deleteRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['QuestionSetControllerApi.deleteQuestionSet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {QuestionSetEditRequest} questionSetEditRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async editQuestionSet(questionSetEditRequest: QuestionSetEditRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseBoolean>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.editQuestionSet(questionSetEditRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['QuestionSetControllerApi.editQuestionSet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getQuestionSetById(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseQuestionSet>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getQuestionSetById(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['QuestionSetControllerApi.getQuestionSetById']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getQuestionSetVOById(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseQuestionSetVO>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getQuestionSetVOById(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['QuestionSetControllerApi.getQuestionSetVOById']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {QuestionSetQueryRequest} questionSetQueryRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listMyQuestionSetVOByPage(questionSetQueryRequest: QuestionSetQueryRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponsePageQuestionSetVO>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listMyQuestionSetVOByPage(questionSetQueryRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['QuestionSetControllerApi.listMyQuestionSetVOByPage']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {QuestionSetQueryRequest} questionSetQueryRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listQuestionSetByPage(questionSetQueryRequest: QuestionSetQueryRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponsePageQuestionSet>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listQuestionSetByPage(questionSetQueryRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['QuestionSetControllerApi.listQuestionSetByPage']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {QuestionSetQueryRequest} questionSetQueryRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listQuestionSetVOByPage(questionSetQueryRequest: QuestionSetQueryRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponsePageQuestionSetVO>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listQuestionSetVOByPage(questionSetQueryRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['QuestionSetControllerApi.listQuestionSetVOByPage']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async redirectDocHtml(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.redirectDocHtml(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['QuestionSetControllerApi.redirectDocHtml']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async redirectOpenApiDocs(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.redirectOpenApiDocs(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['QuestionSetControllerApi.redirectOpenApiDocs']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {QuestionSetItemRemoveRequest} questionSetItemRemoveRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async removeQuestionFromSet(questionSetItemRemoveRequest: QuestionSetItemRemoveRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseBoolean>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.removeQuestionFromSet(questionSetItemRemoveRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['QuestionSetControllerApi.removeQuestionFromSet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {QuestionSetUpdateRequest} questionSetUpdateRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateQuestionSet(questionSetUpdateRequest: QuestionSetUpdateRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseBoolean>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateQuestionSet(questionSetUpdateRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['QuestionSetControllerApi.updateQuestionSet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * QuestionSetControllerApi - factory interface
 */
export const QuestionSetControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = QuestionSetControllerApiFp(configuration)
    return {
        /**
         * 
         * @param {QuestionSetAddRequest} questionSetAddRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addQuestionSet(questionSetAddRequest: QuestionSetAddRequest, options?: RawAxiosRequestConfig): AxiosPromise<BaseResponseLong> {
            return localVarFp.addQuestionSet(questionSetAddRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {QuestionSetItemAddRequest} questionSetItemAddRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addQuestionToSet(questionSetItemAddRequest: QuestionSetItemAddRequest, options?: RawAxiosRequestConfig): AxiosPromise<BaseResponseBoolean> {
            return localVarFp.addQuestionToSet(questionSetItemAddRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {DeleteRequest} deleteRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteQuestionSet(deleteRequest: DeleteRequest, options?: RawAxiosRequestConfig): AxiosPromise<BaseResponseBoolean> {
            return localVarFp.deleteQuestionSet(deleteRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {QuestionSetEditRequest} questionSetEditRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        editQuestionSet(questionSetEditRequest: QuestionSetEditRequest, options?: RawAxiosRequestConfig): AxiosPromise<BaseResponseBoolean> {
            return localVarFp.editQuestionSet(questionSetEditRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getQuestionSetById(id: string, options?: RawAxiosRequestConfig): AxiosPromise<BaseResponseQuestionSet> {
            return localVarFp.getQuestionSetById(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getQuestionSetVOById(id: string, options?: RawAxiosRequestConfig): AxiosPromise<BaseResponseQuestionSetVO> {
            return localVarFp.getQuestionSetVOById(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {QuestionSetQueryRequest} questionSetQueryRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listMyQuestionSetVOByPage(questionSetQueryRequest: QuestionSetQueryRequest, options?: RawAxiosRequestConfig): AxiosPromise<BaseResponsePageQuestionSetVO> {
            return localVarFp.listMyQuestionSetVOByPage(questionSetQueryRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {QuestionSetQueryRequest} questionSetQueryRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listQuestionSetByPage(questionSetQueryRequest: QuestionSetQueryRequest, options?: RawAxiosRequestConfig): AxiosPromise<BaseResponsePageQuestionSet> {
            return localVarFp.listQuestionSetByPage(questionSetQueryRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {QuestionSetQueryRequest} questionSetQueryRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listQuestionSetVOByPage(questionSetQueryRequest: QuestionSetQueryRequest, options?: RawAxiosRequestConfig): AxiosPromise<BaseResponsePageQuestionSetVO> {
            return localVarFp.listQuestionSetVOByPage(questionSetQueryRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        redirectDocHtml(options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.redirectDocHtml(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        redirectOpenApiDocs(options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.redirectOpenApiDocs(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {QuestionSetItemRemoveRequest} questionSetItemRemoveRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        removeQuestionFromSet(questionSetItemRemoveRequest: QuestionSetItemRemoveRequest, options?: RawAxiosRequestConfig): AxiosPromise<BaseResponseBoolean> {
            return localVarFp.removeQuestionFromSet(questionSetItemRemoveRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {QuestionSetUpdateRequest} questionSetUpdateRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateQuestionSet(questionSetUpdateRequest: QuestionSetUpdateRequest, options?: RawAxiosRequestConfig): AxiosPromise<BaseResponseBoolean> {
            return localVarFp.updateQuestionSet(questionSetUpdateRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * QuestionSetControllerApi - object-oriented interface
 */
export class QuestionSetControllerApi extends BaseAPI {
    /**
     * 
     * @param {QuestionSetAddRequest} questionSetAddRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public addQuestionSet(questionSetAddRequest: QuestionSetAddRequest, options?: RawAxiosRequestConfig) {
        return QuestionSetControllerApiFp(this.configuration).addQuestionSet(questionSetAddRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {QuestionSetItemAddRequest} questionSetItemAddRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public addQuestionToSet(questionSetItemAddRequest: QuestionSetItemAddRequest, options?: RawAxiosRequestConfig) {
        return QuestionSetControllerApiFp(this.configuration).addQuestionToSet(questionSetItemAddRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {DeleteRequest} deleteRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public deleteQuestionSet(deleteRequest: DeleteRequest, options?: RawAxiosRequestConfig) {
        return QuestionSetControllerApiFp(this.configuration).deleteQuestionSet(deleteRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {QuestionSetEditRequest} questionSetEditRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public editQuestionSet(questionSetEditRequest: QuestionSetEditRequest, options?: RawAxiosRequestConfig) {
        return QuestionSetControllerApiFp(this.configuration).editQuestionSet(questionSetEditRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getQuestionSetById(id: string, options?: RawAxiosRequestConfig) {
        return QuestionSetControllerApiFp(this.configuration).getQuestionSetById(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getQuestionSetVOById(id: string, options?: RawAxiosRequestConfig) {
        return QuestionSetControllerApiFp(this.configuration).getQuestionSetVOById(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {QuestionSetQueryRequest} questionSetQueryRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public listMyQuestionSetVOByPage(questionSetQueryRequest: QuestionSetQueryRequest, options?: RawAxiosRequestConfig) {
        return QuestionSetControllerApiFp(this.configuration).listMyQuestionSetVOByPage(questionSetQueryRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {QuestionSetQueryRequest} questionSetQueryRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public listQuestionSetByPage(questionSetQueryRequest: QuestionSetQueryRequest, options?: RawAxiosRequestConfig) {
        return QuestionSetControllerApiFp(this.configuration).listQuestionSetByPage(questionSetQueryRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {QuestionSetQueryRequest} questionSetQueryRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public listQuestionSetVOByPage(questionSetQueryRequest: QuestionSetQueryRequest, options?: RawAxiosRequestConfig) {
        return QuestionSetControllerApiFp(this.configuration).listQuestionSetVOByPage(questionSetQueryRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public redirectDocHtml(options?: RawAxiosRequestConfig) {
        return QuestionSetControllerApiFp(this.configuration).redirectDocHtml(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public redirectOpenApiDocs(options?: RawAxiosRequestConfig) {
        return QuestionSetControllerApiFp(this.configuration).redirectOpenApiDocs(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {QuestionSetItemRemoveRequest} questionSetItemRemoveRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public removeQuestionFromSet(questionSetItemRemoveRequest: QuestionSetItemRemoveRequest, options?: RawAxiosRequestConfig) {
        return QuestionSetControllerApiFp(this.configuration).removeQuestionFromSet(questionSetItemRemoveRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {QuestionSetUpdateRequest} questionSetUpdateRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public updateQuestionSet(questionSetUpdateRequest: QuestionSetUpdateRequest, options?: RawAxiosRequestConfig) {
        return QuestionSetControllerApiFp(this.configuration).updateQuestionSet(questionSetUpdateRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

