/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CaptchaVOPointListInner } from './captcha-vopoint-list-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { PointVO } from './point-vo';

export interface CaptchaVO {
    'captchaId'?: string;
    'projectCode'?: string;
    'captchaType'?: string;
    'captchaOriginalPath'?: string;
    'captchaFontType'?: string;
    'captchaFontSize'?: number;
    'secretKey'?: string;
    'originalImageBase64'?: string;
    'point'?: PointVO;
    'jigsawImageBase64'?: string;
    'wordList'?: Array<string>;
    'pointList'?: Array<CaptchaVOPointListInner>;
    'pointJson'?: string;
    'token'?: string;
    'result'?: boolean;
    'captchaVerification'?: string;
    'clientUid'?: string;
    'ts'?: number;
    'browserInfo'?: string;
}

