/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface ResponseModel {
    'repCode'?: string;
    'repMsg'?: string;
    'repData'?: object;
    'success'?: boolean;
    'repCodeEnum'?: ResponseModelRepCodeEnumEnum;
}

export const ResponseModelRepCodeEnumEnum = {
    Success: 'SUCCESS',
    Error: 'ERROR',
    Exception: 'EXCEPTION',
    BlankError: 'BLANK_ERROR',
    NullError: 'NULL_ERROR',
    NotNullError: 'NOT_NULL_ERROR',
    NotExistError: 'NOT_EXIST_ERROR',
    ExistError: 'EXIST_ERROR',
    ParamTypeError: 'PARAM_TYPE_ERROR',
    ParamFormatError: 'PARAM_FORMAT_ERROR',
    ApiCaptchaInvalid: 'API_CAPTCHA_INVALID',
    ApiCaptchaCoordinateError: 'API_CAPTCHA_COORDINATE_ERROR',
    ApiCaptchaError: 'API_CAPTCHA_ERROR',
    ApiCaptchaBasemapNull: 'API_CAPTCHA_BASEMAP_NULL',
    ApiReqLimitGetError: 'API_REQ_LIMIT_GET_ERROR',
    ApiReqInvalid: 'API_REQ_INVALID',
    ApiReqLockGetError: 'API_REQ_LOCK_GET_ERROR',
    ApiReqLimitCheckError: 'API_REQ_LIMIT_CHECK_ERROR',
    ApiReqLimitVerifyError: 'API_REQ_LIMIT_VERIFY_ERROR'
} as const;

export type ResponseModelRepCodeEnumEnum = typeof ResponseModelRepCodeEnumEnum[keyof typeof ResponseModelRepCodeEnumEnum];


