/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CodeTemplate } from './code-template';
// May contain unused imports in some cases
// @ts-ignore
import type { JudgeCase } from './judge-case';
// May contain unused imports in some cases
// @ts-ignore
import type { JudgeConfig } from './judge-config';

export interface QuestionUpdateRequest {
    'id'?: string;
    'title'?: string;
    'content'?: string;
    'tags'?: Array<string>;
    'judgeConfig'?: JudgeConfig;
    'judgeCase'?: Array<JudgeCase>;
    'answer'?: string;
    'codeTemplate'?: CodeTemplate;
}

