/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface QuestionSubmit {
    'id'?: string;
    'questionId'?: string;
    'userId'?: string;
    'language'?: string;
    'code'?: string;
    'status'?: number;
    'judgeInfo'?: string;
    'createTime'?: string;
    'updateTime'?: string;
    'isDelete'?: number;
    'outputResult'?: string;
}

