/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { BaseResponseBoolean } from '../model';
// @ts-ignore
import type { BaseResponseInteger } from '../model';
// @ts-ignore
import type { BaseResponseLong } from '../model';
// @ts-ignore
import type { BaseResponsePagePost } from '../model';
// @ts-ignore
import type { BaseResponsePagePostVO } from '../model';
// @ts-ignore
import type { BaseResponsePostVO } from '../model';
// @ts-ignore
import type { DeleteRequest } from '../model';
// @ts-ignore
import type { Post } from '../model';
// @ts-ignore
import type { PostAddRequest } from '../model';
// @ts-ignore
import type { PostEditRequest } from '../model';
// @ts-ignore
import type { PostFavourAddRequest } from '../model';
// @ts-ignore
import type { PostFavourQueryRequest } from '../model';
// @ts-ignore
import type { PostQueryRequest } from '../model';
// @ts-ignore
import type { PostThumbAddRequest } from '../model';
// @ts-ignore
import type { PostUpdateRequest } from '../model';
/**
 * DefaultApi - axios parameter creator
 */
export const DefaultApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary 创建帖子
         * @param {PostAddRequest} postAddRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addPost: async (postAddRequest: PostAddRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'postAddRequest' is not null or undefined
            assertParamExists('addPost', 'postAddRequest', postAddRequest)
            const localVarPath = `/add`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(postAddRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 删除帖子
         * @param {DeleteRequest} deleteRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deletePost: async (deleteRequest: DeleteRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'deleteRequest' is not null or undefined
            assertParamExists('deletePost', 'deleteRequest', deleteRequest)
            const localVarPath = `/delete`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(deleteRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 收藏/取消收藏
         * @param {PostFavourAddRequest} postFavourAddRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        doPostFavour: async (postFavourAddRequest: PostFavourAddRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'postFavourAddRequest' is not null or undefined
            assertParamExists('doPostFavour', 'postFavourAddRequest', postFavourAddRequest)
            const localVarPath = `/favour`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(postFavourAddRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 点赞/取消点赞
         * @param {PostThumbAddRequest} postThumbAddRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        doThumb: async (postThumbAddRequest: PostThumbAddRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'postThumbAddRequest' is not null or undefined
            assertParamExists('doThumb', 'postThumbAddRequest', postThumbAddRequest)
            const localVarPath = `/thumb`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(postThumbAddRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 编辑帖子
         * @param {PostEditRequest} postEditRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        editPost: async (postEditRequest: PostEditRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'postEditRequest' is not null or undefined
            assertParamExists('editPost', 'postEditRequest', postEditRequest)
            const localVarPath = `/edit`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(postEditRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 根据id获取帖子
         * @param {string} postId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getById: async (postId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'postId' is not null or undefined
            assertParamExists('getById', 'postId', postId)
            const localVarPath = `/inner/get/id`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (postId !== undefined) {
                localVarQueryParameter['postId'] = postId;
            }

            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 根据id获取帖子
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getPostVOById: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('getPostVOById', 'id', id)
            const localVarPath = `/get/vo`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (id !== undefined) {
                localVarQueryParameter['id'] = id;
            }

            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 通过id集合查询帖子集合
         * @param {Array<string>} idList 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listByIds: async (idList: Array<string>, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'idList' is not null or undefined
            assertParamExists('listByIds', 'idList', idList)
            const localVarPath = `/inner/list/id`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (idList) {
                localVarQueryParameter['idList'] = idList;
            }

            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 获取用户收藏的帖子列表
         * @param {PostFavourQueryRequest} postFavourQueryRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listFavourPostByPage: async (postFavourQueryRequest: PostFavourQueryRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'postFavourQueryRequest' is not null or undefined
            assertParamExists('listFavourPostByPage', 'postFavourQueryRequest', postFavourQueryRequest)
            const localVarPath = `/favour/list/page`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(postFavourQueryRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 获取我收藏的帖子列表
         * @param {PostQueryRequest} postQueryRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listMyFavourPostByPage: async (postQueryRequest: PostQueryRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'postQueryRequest' is not null or undefined
            assertParamExists('listMyFavourPostByPage', 'postQueryRequest', postQueryRequest)
            const localVarPath = `/favour/my/list/page`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(postQueryRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 分页获取我的帖子列表
         * @param {PostQueryRequest} postQueryRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listMyPostVOByPage: async (postQueryRequest: PostQueryRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'postQueryRequest' is not null or undefined
            assertParamExists('listMyPostVOByPage', 'postQueryRequest', postQueryRequest)
            const localVarPath = `/my/list/page/vo`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(postQueryRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 分页获取帖子列表（管理员）
         * @param {PostQueryRequest} postQueryRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listPostByPage: async (postQueryRequest: PostQueryRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'postQueryRequest' is not null or undefined
            assertParamExists('listPostByPage', 'postQueryRequest', postQueryRequest)
            const localVarPath = `/list/page`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(postQueryRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 分页获取帖子列表（封装类）
         * @param {PostQueryRequest} postQueryRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listPostVOByPage: async (postQueryRequest: PostQueryRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'postQueryRequest' is not null or undefined
            assertParamExists('listPostVOByPage', 'postQueryRequest', postQueryRequest)
            const localVarPath = `/list/page/vo`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(postQueryRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 更新帖子（管理员）
         * @param {PostUpdateRequest} postUpdateRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updatePost: async (postUpdateRequest: PostUpdateRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'postUpdateRequest' is not null or undefined
            assertParamExists('updatePost', 'postUpdateRequest', postUpdateRequest)
            const localVarPath = `/update`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(postUpdateRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DefaultApi - functional programming interface
 */
export const DefaultApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DefaultApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary 创建帖子
         * @param {PostAddRequest} postAddRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async addPost(postAddRequest: PostAddRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseLong>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.addPost(postAddRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.addPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary 删除帖子
         * @param {DeleteRequest} deleteRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deletePost(deleteRequest: DeleteRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseBoolean>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deletePost(deleteRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.deletePost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary 收藏/取消收藏
         * @param {PostFavourAddRequest} postFavourAddRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async doPostFavour(postFavourAddRequest: PostFavourAddRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseInteger>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.doPostFavour(postFavourAddRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.doPostFavour']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary 点赞/取消点赞
         * @param {PostThumbAddRequest} postThumbAddRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async doThumb(postThumbAddRequest: PostThumbAddRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseInteger>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.doThumb(postThumbAddRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.doThumb']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary 编辑帖子
         * @param {PostEditRequest} postEditRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async editPost(postEditRequest: PostEditRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseBoolean>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.editPost(postEditRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.editPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary 根据id获取帖子
         * @param {string} postId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getById(postId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Post>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getById(postId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.getById']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary 根据id获取帖子
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getPostVOById(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponsePostVO>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getPostVOById(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.getPostVOById']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary 通过id集合查询帖子集合
         * @param {Array<string>} idList 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listByIds(idList: Array<string>, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<Post>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listByIds(idList, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.listByIds']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary 获取用户收藏的帖子列表
         * @param {PostFavourQueryRequest} postFavourQueryRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listFavourPostByPage(postFavourQueryRequest: PostFavourQueryRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponsePagePostVO>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listFavourPostByPage(postFavourQueryRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.listFavourPostByPage']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary 获取我收藏的帖子列表
         * @param {PostQueryRequest} postQueryRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listMyFavourPostByPage(postQueryRequest: PostQueryRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponsePagePostVO>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listMyFavourPostByPage(postQueryRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.listMyFavourPostByPage']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary 分页获取我的帖子列表
         * @param {PostQueryRequest} postQueryRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listMyPostVOByPage(postQueryRequest: PostQueryRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponsePagePostVO>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listMyPostVOByPage(postQueryRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.listMyPostVOByPage']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary 分页获取帖子列表（管理员）
         * @param {PostQueryRequest} postQueryRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listPostByPage(postQueryRequest: PostQueryRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponsePagePost>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listPostByPage(postQueryRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.listPostByPage']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary 分页获取帖子列表（封装类）
         * @param {PostQueryRequest} postQueryRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listPostVOByPage(postQueryRequest: PostQueryRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponsePagePostVO>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listPostVOByPage(postQueryRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.listPostVOByPage']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary 更新帖子（管理员）
         * @param {PostUpdateRequest} postUpdateRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updatePost(postUpdateRequest: PostUpdateRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseBoolean>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updatePost(postUpdateRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.updatePost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * DefaultApi - factory interface
 */
export const DefaultApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DefaultApiFp(configuration)
    return {
        /**
         * 
         * @summary 创建帖子
         * @param {PostAddRequest} postAddRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addPost(postAddRequest: PostAddRequest, options?: RawAxiosRequestConfig): AxiosPromise<BaseResponseLong> {
            return localVarFp.addPost(postAddRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 删除帖子
         * @param {DeleteRequest} deleteRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deletePost(deleteRequest: DeleteRequest, options?: RawAxiosRequestConfig): AxiosPromise<BaseResponseBoolean> {
            return localVarFp.deletePost(deleteRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 收藏/取消收藏
         * @param {PostFavourAddRequest} postFavourAddRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        doPostFavour(postFavourAddRequest: PostFavourAddRequest, options?: RawAxiosRequestConfig): AxiosPromise<BaseResponseInteger> {
            return localVarFp.doPostFavour(postFavourAddRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 点赞/取消点赞
         * @param {PostThumbAddRequest} postThumbAddRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        doThumb(postThumbAddRequest: PostThumbAddRequest, options?: RawAxiosRequestConfig): AxiosPromise<BaseResponseInteger> {
            return localVarFp.doThumb(postThumbAddRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 编辑帖子
         * @param {PostEditRequest} postEditRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        editPost(postEditRequest: PostEditRequest, options?: RawAxiosRequestConfig): AxiosPromise<BaseResponseBoolean> {
            return localVarFp.editPost(postEditRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 根据id获取帖子
         * @param {string} postId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getById(postId: string, options?: RawAxiosRequestConfig): AxiosPromise<Post> {
            return localVarFp.getById(postId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 根据id获取帖子
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getPostVOById(id: string, options?: RawAxiosRequestConfig): AxiosPromise<BaseResponsePostVO> {
            return localVarFp.getPostVOById(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 通过id集合查询帖子集合
         * @param {Array<string>} idList 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listByIds(idList: Array<string>, options?: RawAxiosRequestConfig): AxiosPromise<Array<Post>> {
            return localVarFp.listByIds(idList, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 获取用户收藏的帖子列表
         * @param {PostFavourQueryRequest} postFavourQueryRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listFavourPostByPage(postFavourQueryRequest: PostFavourQueryRequest, options?: RawAxiosRequestConfig): AxiosPromise<BaseResponsePagePostVO> {
            return localVarFp.listFavourPostByPage(postFavourQueryRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 获取我收藏的帖子列表
         * @param {PostQueryRequest} postQueryRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listMyFavourPostByPage(postQueryRequest: PostQueryRequest, options?: RawAxiosRequestConfig): AxiosPromise<BaseResponsePagePostVO> {
            return localVarFp.listMyFavourPostByPage(postQueryRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 分页获取我的帖子列表
         * @param {PostQueryRequest} postQueryRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listMyPostVOByPage(postQueryRequest: PostQueryRequest, options?: RawAxiosRequestConfig): AxiosPromise<BaseResponsePagePostVO> {
            return localVarFp.listMyPostVOByPage(postQueryRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 分页获取帖子列表（管理员）
         * @param {PostQueryRequest} postQueryRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listPostByPage(postQueryRequest: PostQueryRequest, options?: RawAxiosRequestConfig): AxiosPromise<BaseResponsePagePost> {
            return localVarFp.listPostByPage(postQueryRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 分页获取帖子列表（封装类）
         * @param {PostQueryRequest} postQueryRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listPostVOByPage(postQueryRequest: PostQueryRequest, options?: RawAxiosRequestConfig): AxiosPromise<BaseResponsePagePostVO> {
            return localVarFp.listPostVOByPage(postQueryRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 更新帖子（管理员）
         * @param {PostUpdateRequest} postUpdateRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updatePost(postUpdateRequest: PostUpdateRequest, options?: RawAxiosRequestConfig): AxiosPromise<BaseResponseBoolean> {
            return localVarFp.updatePost(postUpdateRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DefaultApi - object-oriented interface
 */
export class DefaultApi extends BaseAPI {
    /**
     * 
     * @summary 创建帖子
     * @param {PostAddRequest} postAddRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public addPost(postAddRequest: PostAddRequest, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).addPost(postAddRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 删除帖子
     * @param {DeleteRequest} deleteRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public deletePost(deleteRequest: DeleteRequest, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).deletePost(deleteRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 收藏/取消收藏
     * @param {PostFavourAddRequest} postFavourAddRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public doPostFavour(postFavourAddRequest: PostFavourAddRequest, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).doPostFavour(postFavourAddRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 点赞/取消点赞
     * @param {PostThumbAddRequest} postThumbAddRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public doThumb(postThumbAddRequest: PostThumbAddRequest, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).doThumb(postThumbAddRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 编辑帖子
     * @param {PostEditRequest} postEditRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public editPost(postEditRequest: PostEditRequest, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).editPost(postEditRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 根据id获取帖子
     * @param {string} postId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getById(postId: string, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).getById(postId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 根据id获取帖子
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getPostVOById(id: string, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).getPostVOById(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 通过id集合查询帖子集合
     * @param {Array<string>} idList 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public listByIds(idList: Array<string>, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).listByIds(idList, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 获取用户收藏的帖子列表
     * @param {PostFavourQueryRequest} postFavourQueryRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public listFavourPostByPage(postFavourQueryRequest: PostFavourQueryRequest, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).listFavourPostByPage(postFavourQueryRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 获取我收藏的帖子列表
     * @param {PostQueryRequest} postQueryRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public listMyFavourPostByPage(postQueryRequest: PostQueryRequest, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).listMyFavourPostByPage(postQueryRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 分页获取我的帖子列表
     * @param {PostQueryRequest} postQueryRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public listMyPostVOByPage(postQueryRequest: PostQueryRequest, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).listMyPostVOByPage(postQueryRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 分页获取帖子列表（管理员）
     * @param {PostQueryRequest} postQueryRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public listPostByPage(postQueryRequest: PostQueryRequest, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).listPostByPage(postQueryRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 分页获取帖子列表（封装类）
     * @param {PostQueryRequest} postQueryRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public listPostVOByPage(postQueryRequest: PostQueryRequest, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).listPostVOByPage(postQueryRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 更新帖子（管理员）
     * @param {PostUpdateRequest} postUpdateRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public updatePost(postUpdateRequest: PostUpdateRequest, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).updatePost(postUpdateRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

