/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { CaptchaVO } from '../model';
// @ts-ignore
import type { ResponseModel } from '../model';
/**
 * CaptchaControllerApi - axios parameter creator
 */
export const CaptchaControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {CaptchaVO} captchaVO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        check: async (captchaVO: CaptchaVO, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'captchaVO' is not null or undefined
            assertParamExists('check', 'captchaVO', captchaVO)
            const localVarPath = `/captcha/check`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(captchaVO, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {CaptchaVO} captchaVO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        get: async (captchaVO: CaptchaVO, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'captchaVO' is not null or undefined
            assertParamExists('get', 'captchaVO', captchaVO)
            const localVarPath = `/captcha/get`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(captchaVO, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * CaptchaControllerApi - functional programming interface
 */
export const CaptchaControllerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = CaptchaControllerApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {CaptchaVO} captchaVO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async check(captchaVO: CaptchaVO, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResponseModel>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.check(captchaVO, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CaptchaControllerApi.check']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {CaptchaVO} captchaVO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async get(captchaVO: CaptchaVO, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResponseModel>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.get(captchaVO, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CaptchaControllerApi.get']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * CaptchaControllerApi - factory interface
 */
export const CaptchaControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = CaptchaControllerApiFp(configuration)
    return {
        /**
         * 
         * @param {CaptchaVO} captchaVO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        check(captchaVO: CaptchaVO, options?: RawAxiosRequestConfig): AxiosPromise<ResponseModel> {
            return localVarFp.check(captchaVO, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {CaptchaVO} captchaVO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        get(captchaVO: CaptchaVO, options?: RawAxiosRequestConfig): AxiosPromise<ResponseModel> {
            return localVarFp.get(captchaVO, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * CaptchaControllerApi - object-oriented interface
 */
export class CaptchaControllerApi extends BaseAPI {
    /**
     * 
     * @param {CaptchaVO} captchaVO 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public check(captchaVO: CaptchaVO, options?: RawAxiosRequestConfig) {
        return CaptchaControllerApiFp(this.configuration).check(captchaVO, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {CaptchaVO} captchaVO 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public get(captchaVO: CaptchaVO, options?: RawAxiosRequestConfig) {
        return CaptchaControllerApiFp(this.configuration).get(captchaVO, options).then((request) => request(this.axios, this.basePath));
    }
}

