/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { DoJudgeRequest } from '../model';
// @ts-ignore
import type { QuestionSubmitVO } from '../model';
/**
 * InnerJudgeControllerApi - axios parameter creator
 */
export const InnerJudgeControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {DoJudgeRequest} doJudgeRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        doJudge: async (doJudgeRequest: DoJudgeRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'doJudgeRequest' is not null or undefined
            assertParamExists('doJudge', 'doJudgeRequest', doJudgeRequest)
            const localVarPath = `/inner/do`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(doJudgeRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * InnerJudgeControllerApi - functional programming interface
 */
export const InnerJudgeControllerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = InnerJudgeControllerApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {DoJudgeRequest} doJudgeRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async doJudge(doJudgeRequest: DoJudgeRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<QuestionSubmitVO>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.doJudge(doJudgeRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['InnerJudgeControllerApi.doJudge']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * InnerJudgeControllerApi - factory interface
 */
export const InnerJudgeControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = InnerJudgeControllerApiFp(configuration)
    return {
        /**
         * 
         * @param {DoJudgeRequest} doJudgeRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        doJudge(doJudgeRequest: DoJudgeRequest, options?: RawAxiosRequestConfig): AxiosPromise<QuestionSubmitVO> {
            return localVarFp.doJudge(doJudgeRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * InnerJudgeControllerApi - object-oriented interface
 */
export class InnerJudgeControllerApi extends BaseAPI {
    /**
     * 
     * @param {DoJudgeRequest} doJudgeRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public doJudge(doJudgeRequest: DoJudgeRequest, options?: RawAxiosRequestConfig) {
        return InnerJudgeControllerApiFp(this.configuration).doJudge(doJudgeRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

