/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { BaseResponseBoolean } from '../model';
// @ts-ignore
import type { BaseResponseLong } from '../model';
// @ts-ignore
import type { BaseResponsePageRoom } from '../model';
// @ts-ignore
import type { BaseResponsePageRoomVO } from '../model';
// @ts-ignore
import type { BaseResponseRoom } from '../model';
// @ts-ignore
import type { BaseResponseRoomAuthRequest } from '../model';
// @ts-ignore
import type { BaseResponseRoomVO } from '../model';
// @ts-ignore
import type { DeleteRequest } from '../model';
// @ts-ignore
import type { RoomAddRequest } from '../model';
// @ts-ignore
import type { RoomAuthRequest } from '../model';
// @ts-ignore
import type { RoomEditRequest } from '../model';
// @ts-ignore
import type { RoomJoinRequest } from '../model';
// @ts-ignore
import type { RoomQueryRequest } from '../model';
// @ts-ignore
import type { RoomQuitRequest } from '../model';
// @ts-ignore
import type { RoomTransferRequest } from '../model';
// @ts-ignore
import type { RoomUpdateRequest } from '../model';
/**
 * RoomControllerApi - axios parameter creator
 */
export const RoomControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {RoomAddRequest} roomAddRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addRoom: async (roomAddRequest: RoomAddRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'roomAddRequest' is not null or undefined
            assertParamExists('addRoom', 'roomAddRequest', roomAddRequest)
            const localVarPath = `/add`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(roomAddRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {RoomAuthRequest} roomAuthRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        auth: async (roomAuthRequest: RoomAuthRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'roomAuthRequest' is not null or undefined
            assertParamExists('auth', 'roomAuthRequest', roomAuthRequest)
            const localVarPath = `/auth`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(roomAuthRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {DeleteRequest} deleteRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteRoom: async (deleteRequest: DeleteRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'deleteRequest' is not null or undefined
            assertParamExists('deleteRoom', 'deleteRequest', deleteRequest)
            const localVarPath = `/delete`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(deleteRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {RoomEditRequest} roomEditRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        editRoom: async (roomEditRequest: RoomEditRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'roomEditRequest' is not null or undefined
            assertParamExists('editRoom', 'roomEditRequest', roomEditRequest)
            const localVarPath = `/edit`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(roomEditRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} roomId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        generateAuthToken: async (roomId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'roomId' is not null or undefined
            assertParamExists('generateAuthToken', 'roomId', roomId)
            const localVarPath = `/auth/token`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (roomId !== undefined) {
                localVarQueryParameter['roomId'] = roomId;
            }

            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getRoomById: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('getRoomById', 'id', id)
            const localVarPath = `/get`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (id !== undefined) {
                localVarQueryParameter['id'] = id;
            }

            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getRoomVOById: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('getRoomVOById', 'id', id)
            const localVarPath = `/get/vo`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (id !== undefined) {
                localVarQueryParameter['id'] = id;
            }

            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {RoomJoinRequest} roomJoinRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        joinRoom: async (roomJoinRequest: RoomJoinRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'roomJoinRequest' is not null or undefined
            assertParamExists('joinRoom', 'roomJoinRequest', roomJoinRequest)
            const localVarPath = `/join`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(roomJoinRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {RoomQueryRequest} roomQueryRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listMyRoomVOByPage: async (roomQueryRequest: RoomQueryRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'roomQueryRequest' is not null or undefined
            assertParamExists('listMyRoomVOByPage', 'roomQueryRequest', roomQueryRequest)
            const localVarPath = `/my/list/page/vo`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(roomQueryRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {RoomQueryRequest} roomQueryRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listRoomByPage: async (roomQueryRequest: RoomQueryRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'roomQueryRequest' is not null or undefined
            assertParamExists('listRoomByPage', 'roomQueryRequest', roomQueryRequest)
            const localVarPath = `/list/page`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(roomQueryRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {RoomQueryRequest} roomQueryRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listRoomVOByPage: async (roomQueryRequest: RoomQueryRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'roomQueryRequest' is not null or undefined
            assertParamExists('listRoomVOByPage', 'roomQueryRequest', roomQueryRequest)
            const localVarPath = `/list/page/vo`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(roomQueryRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {RoomQuitRequest} roomQuitRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        quitRoom: async (roomQuitRequest: RoomQuitRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'roomQuitRequest' is not null or undefined
            assertParamExists('quitRoom', 'roomQuitRequest', roomQuitRequest)
            const localVarPath = `/quit`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(roomQuitRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {RoomTransferRequest} roomTransferRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        transferLeader: async (roomTransferRequest: RoomTransferRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'roomTransferRequest' is not null or undefined
            assertParamExists('transferLeader', 'roomTransferRequest', roomTransferRequest)
            const localVarPath = `/transfer`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(roomTransferRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {RoomUpdateRequest} roomUpdateRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateRoom: async (roomUpdateRequest: RoomUpdateRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'roomUpdateRequest' is not null or undefined
            assertParamExists('updateRoom', 'roomUpdateRequest', roomUpdateRequest)
            const localVarPath = `/update`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(roomUpdateRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * RoomControllerApi - functional programming interface
 */
export const RoomControllerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = RoomControllerApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {RoomAddRequest} roomAddRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async addRoom(roomAddRequest: RoomAddRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseLong>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.addRoom(roomAddRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RoomControllerApi.addRoom']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {RoomAuthRequest} roomAuthRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async auth(roomAuthRequest: RoomAuthRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseBoolean>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.auth(roomAuthRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RoomControllerApi.auth']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {DeleteRequest} deleteRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteRoom(deleteRequest: DeleteRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseBoolean>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteRoom(deleteRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RoomControllerApi.deleteRoom']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {RoomEditRequest} roomEditRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async editRoom(roomEditRequest: RoomEditRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseBoolean>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.editRoom(roomEditRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RoomControllerApi.editRoom']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} roomId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async generateAuthToken(roomId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseRoomAuthRequest>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.generateAuthToken(roomId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RoomControllerApi.generateAuthToken']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getRoomById(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseRoom>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getRoomById(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RoomControllerApi.getRoomById']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getRoomVOById(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseRoomVO>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getRoomVOById(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RoomControllerApi.getRoomVOById']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {RoomJoinRequest} roomJoinRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async joinRoom(roomJoinRequest: RoomJoinRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseBoolean>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.joinRoom(roomJoinRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RoomControllerApi.joinRoom']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {RoomQueryRequest} roomQueryRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listMyRoomVOByPage(roomQueryRequest: RoomQueryRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponsePageRoomVO>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listMyRoomVOByPage(roomQueryRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RoomControllerApi.listMyRoomVOByPage']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {RoomQueryRequest} roomQueryRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listRoomByPage(roomQueryRequest: RoomQueryRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponsePageRoom>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listRoomByPage(roomQueryRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RoomControllerApi.listRoomByPage']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {RoomQueryRequest} roomQueryRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listRoomVOByPage(roomQueryRequest: RoomQueryRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponsePageRoomVO>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listRoomVOByPage(roomQueryRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RoomControllerApi.listRoomVOByPage']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {RoomQuitRequest} roomQuitRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async quitRoom(roomQuitRequest: RoomQuitRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseBoolean>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.quitRoom(roomQuitRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RoomControllerApi.quitRoom']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {RoomTransferRequest} roomTransferRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async transferLeader(roomTransferRequest: RoomTransferRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseBoolean>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.transferLeader(roomTransferRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RoomControllerApi.transferLeader']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {RoomUpdateRequest} roomUpdateRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateRoom(roomUpdateRequest: RoomUpdateRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseBoolean>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateRoom(roomUpdateRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RoomControllerApi.updateRoom']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * RoomControllerApi - factory interface
 */
export const RoomControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = RoomControllerApiFp(configuration)
    return {
        /**
         * 
         * @param {RoomAddRequest} roomAddRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addRoom(roomAddRequest: RoomAddRequest, options?: RawAxiosRequestConfig): AxiosPromise<BaseResponseLong> {
            return localVarFp.addRoom(roomAddRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {RoomAuthRequest} roomAuthRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        auth(roomAuthRequest: RoomAuthRequest, options?: RawAxiosRequestConfig): AxiosPromise<BaseResponseBoolean> {
            return localVarFp.auth(roomAuthRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {DeleteRequest} deleteRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteRoom(deleteRequest: DeleteRequest, options?: RawAxiosRequestConfig): AxiosPromise<BaseResponseBoolean> {
            return localVarFp.deleteRoom(deleteRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {RoomEditRequest} roomEditRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        editRoom(roomEditRequest: RoomEditRequest, options?: RawAxiosRequestConfig): AxiosPromise<BaseResponseBoolean> {
            return localVarFp.editRoom(roomEditRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} roomId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        generateAuthToken(roomId: string, options?: RawAxiosRequestConfig): AxiosPromise<BaseResponseRoomAuthRequest> {
            return localVarFp.generateAuthToken(roomId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getRoomById(id: string, options?: RawAxiosRequestConfig): AxiosPromise<BaseResponseRoom> {
            return localVarFp.getRoomById(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getRoomVOById(id: string, options?: RawAxiosRequestConfig): AxiosPromise<BaseResponseRoomVO> {
            return localVarFp.getRoomVOById(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {RoomJoinRequest} roomJoinRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        joinRoom(roomJoinRequest: RoomJoinRequest, options?: RawAxiosRequestConfig): AxiosPromise<BaseResponseBoolean> {
            return localVarFp.joinRoom(roomJoinRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {RoomQueryRequest} roomQueryRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listMyRoomVOByPage(roomQueryRequest: RoomQueryRequest, options?: RawAxiosRequestConfig): AxiosPromise<BaseResponsePageRoomVO> {
            return localVarFp.listMyRoomVOByPage(roomQueryRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {RoomQueryRequest} roomQueryRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listRoomByPage(roomQueryRequest: RoomQueryRequest, options?: RawAxiosRequestConfig): AxiosPromise<BaseResponsePageRoom> {
            return localVarFp.listRoomByPage(roomQueryRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {RoomQueryRequest} roomQueryRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listRoomVOByPage(roomQueryRequest: RoomQueryRequest, options?: RawAxiosRequestConfig): AxiosPromise<BaseResponsePageRoomVO> {
            return localVarFp.listRoomVOByPage(roomQueryRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {RoomQuitRequest} roomQuitRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        quitRoom(roomQuitRequest: RoomQuitRequest, options?: RawAxiosRequestConfig): AxiosPromise<BaseResponseBoolean> {
            return localVarFp.quitRoom(roomQuitRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {RoomTransferRequest} roomTransferRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        transferLeader(roomTransferRequest: RoomTransferRequest, options?: RawAxiosRequestConfig): AxiosPromise<BaseResponseBoolean> {
            return localVarFp.transferLeader(roomTransferRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {RoomUpdateRequest} roomUpdateRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateRoom(roomUpdateRequest: RoomUpdateRequest, options?: RawAxiosRequestConfig): AxiosPromise<BaseResponseBoolean> {
            return localVarFp.updateRoom(roomUpdateRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * RoomControllerApi - object-oriented interface
 */
export class RoomControllerApi extends BaseAPI {
    /**
     * 
     * @param {RoomAddRequest} roomAddRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public addRoom(roomAddRequest: RoomAddRequest, options?: RawAxiosRequestConfig) {
        return RoomControllerApiFp(this.configuration).addRoom(roomAddRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {RoomAuthRequest} roomAuthRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public auth(roomAuthRequest: RoomAuthRequest, options?: RawAxiosRequestConfig) {
        return RoomControllerApiFp(this.configuration).auth(roomAuthRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {DeleteRequest} deleteRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public deleteRoom(deleteRequest: DeleteRequest, options?: RawAxiosRequestConfig) {
        return RoomControllerApiFp(this.configuration).deleteRoom(deleteRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {RoomEditRequest} roomEditRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public editRoom(roomEditRequest: RoomEditRequest, options?: RawAxiosRequestConfig) {
        return RoomControllerApiFp(this.configuration).editRoom(roomEditRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} roomId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public generateAuthToken(roomId: string, options?: RawAxiosRequestConfig) {
        return RoomControllerApiFp(this.configuration).generateAuthToken(roomId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getRoomById(id: string, options?: RawAxiosRequestConfig) {
        return RoomControllerApiFp(this.configuration).getRoomById(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getRoomVOById(id: string, options?: RawAxiosRequestConfig) {
        return RoomControllerApiFp(this.configuration).getRoomVOById(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {RoomJoinRequest} roomJoinRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public joinRoom(roomJoinRequest: RoomJoinRequest, options?: RawAxiosRequestConfig) {
        return RoomControllerApiFp(this.configuration).joinRoom(roomJoinRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {RoomQueryRequest} roomQueryRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public listMyRoomVOByPage(roomQueryRequest: RoomQueryRequest, options?: RawAxiosRequestConfig) {
        return RoomControllerApiFp(this.configuration).listMyRoomVOByPage(roomQueryRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {RoomQueryRequest} roomQueryRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public listRoomByPage(roomQueryRequest: RoomQueryRequest, options?: RawAxiosRequestConfig) {
        return RoomControllerApiFp(this.configuration).listRoomByPage(roomQueryRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {RoomQueryRequest} roomQueryRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public listRoomVOByPage(roomQueryRequest: RoomQueryRequest, options?: RawAxiosRequestConfig) {
        return RoomControllerApiFp(this.configuration).listRoomVOByPage(roomQueryRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {RoomQuitRequest} roomQuitRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public quitRoom(roomQuitRequest: RoomQuitRequest, options?: RawAxiosRequestConfig) {
        return RoomControllerApiFp(this.configuration).quitRoom(roomQuitRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {RoomTransferRequest} roomTransferRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public transferLeader(roomTransferRequest: RoomTransferRequest, options?: RawAxiosRequestConfig) {
        return RoomControllerApiFp(this.configuration).transferLeader(roomTransferRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {RoomUpdateRequest} roomUpdateRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public updateRoom(roomUpdateRequest: RoomUpdateRequest, options?: RawAxiosRequestConfig) {
        return RoomControllerApiFp(this.configuration).updateRoom(roomUpdateRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

