/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { OrderItem } from './order-item';
// May contain unused imports in some cases
// @ts-ignore
import type { RoomVO } from './room-vo';

export interface PageRoomVO {
    'records'?: Array<RoomVO>;
    'total'?: string;
    'size'?: string;
    'current'?: string;
    /**
     * @deprecated
     */
    'orders'?: Array<OrderItem>;
    /**
     * @deprecated
     */
    'optimizeCountSql'?: boolean;
    /**
     * @deprecated
     */
    'searchCount'?: boolean;
    'optimizeJoinOfCountSql'?: boolean;
    /**
     * @deprecated
     */
    'countId'?: string;
    /**
     * @deprecated
     */
    'maxLimit'?: string;
    'pages'?: string;
}

