/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { RoomMemberVO } from './room-member-vo';
// May contain unused imports in some cases
// @ts-ignore
import type { UserVO } from './user-vo';

export interface RoomVO {
    'id'?: string;
    'name'?: string;
    'description'?: string;
    'mateNum'?: number;
    'userId'?: string;
    'status'?: number;
    'createTime'?: string;
    'currentNum'?: number;
    'userVO'?: UserVO;
    'members'?: Array<RoomMemberVO>;
}

